export const LIS_ETHNICITY_OPTIONS = [
  "Abeling/Abellen/Abelling/Aberling",
  "Adasen",
  "Agta-Agay",
  "Agta-Cimaron / Cimaron",
  "Agta-Dumagat",
  "Agta-Tabangnon",
  "Agta-Taboy",
  "Agutaynon / Agutaynen",
  "Alab",
  "Alangan Mangyan / Alangan",
  "Ambala / Ayta Ambala",
  "Apayao / Yapayao",
  "Aromanen-Manobo / Erumanen Menuvu / Aromanon",
  "Ata",
  "Ata-Manobo",
  "Ati",
  "Ayangan",
  "Ayta / Abiyan",
  "Ayta Sambal",
  "Bagkalot / Bugkalot",
  "Bago",
  "Bagobo",
  "Bagobo-Klata",
  "Bagobo-Tagabawa / Tagabawa",
  "Balangao",
  "Balatoc",
  "Baliwon",
  "Banao",
  "Bangon",
  "Bantoanon",
  "Banwaon",
  "Barlig",
  "Basao",
  "Batak",
  "Batangan Mangyan / Batangan",
  "Belwang",
  "Binongan",
  "Blaan",
  "Bontok / Bontoc",
  "Buhid Mangyan / Buhid",
  "Bukidnon",
  "Butbut",
  "Cagaluan",
  "Cagayanen",
  "Calinga",
  "Cuyunon / Cuyonen",
  "Dacalan",
  "Dagaynen",
  "Dananao",
  "Dibabawon",
  "Dibabeen Mulitaan",
  "Dibaben",
  "Direrayaan",
  "Dumagat / Dumaget",
  "Dumagat-Alta / Alta",
  "Escaya / Eskaya",
  "Gaddang",
  "Gubang",
  "Gubatnon / Gubatnon Mangyan",
  "Guiangan",
  "Guilayon",
  "Guinaang",
  "Halawodnon",
  "Hanunuo / Hanunuo Mangyan",
  "Henanga",
  "Higaonon",
  "Ibaloy / Ibaloi",
  "Ibanag / Ybanag / Iabanag",
  "Ibatan",
  "Ifugao",
  "Ikalahan / Kalanguya Ikalahan",
  "Ilaud",
  "Ilianen / Ilianen Manobo",
  "Ilongot/E'gongot/Igongot",
  "Iraya / Iraya Mangyan",
  "Isarog",
  "Isinai",
  "Isnag / Isneg",
  "Isoroken",
  "Itawes / Itawis / Itawia",
  "Ivatan",
  "Iwak",
  "Kabayukan",
  "Kabihug / Manide",
  "Kadaklan/Kachakran",
  "Kailawan/Kaylawan",
  "Kalagan / Kagan",
  "Kalanguya",
  "Kalibugan / Kolibugan",
  "Kalinga",
  "Kamayo",
  "Kamigin / Kamiguin",
  "Kankanaey / Kankanaey Ibenguet / Kankanaey Iyaplay",
  "Karao",
  "Karulano / Korolanon",
  "Kaunana",
  "Kirenteken",
  "Lahitanen",
  "Lambangian",
  "Lambanglan",
  "Langilan / Talaingod / Talaingod, Langilan",
  "Livunganen",
  "Lubo",
  "Lubuagan",
  "Mabaka",
  "Maeng",
  "Mag-antsi / Ayta Magantsi",
  "Mag-indi / Ayta Mag-indi",
  "Magahat",
  "Magbukon / Ayta Magbukon",
  "Magkunana",
  "Majokayong",
  "Malaweg/Malaueg",
  "Malbong",
  "Mamanwa",
  "Mandaya",
  "Mandek-ey",
  "Mandukayan",
  "Mangali",
  "Mangguangan",
  "Manobo / Menuvu",
  "Manobo-Blit",
  "Manobo-Dulangan / Manobo Dulangan / Dulangan",
  "Manobo-Ubo",
  "Mansaka",
  "Masadiit",
  "Matigsalog / Matigsalug",
  "Mayudan",
  "Molbog",
  "Naneng",
  "Negros Bukidnon",
  "Obu-Manuvu / Obo Monuvu",
  "Pala wan / Pala'wan",
  "Palawan-o",
  "Palawanon",
  "Panay-Bukidnon / Pan-ayanon / Sulod / Budiknon",
  "Parananum",
  "Pulangien / Pulangiyen",
  "Ratagnon / Ratagnon Mangyan",
  "Remontado / Dumagat Remontado",
  "Sadanga",
  "Sakki",
  "Salegseg",
  "Sama",
  "Sama Bangingi",
  "Sama Laut / Dilaut / Sama Badjao / Badjao, Sama Laut / BadjaBadjau",
  "Samal",
  "Sibuyan Mangyan-Tagabukid",
  "Subanen / Subanon",
  "Subanen Ginsalugan",
  "Sumadel",
  "Tabangon",
  "Taboli Manobo",
  "Tadyawan / Tadyawan Mangyan",
  "Tagakaolo / Tagakaulo",
  "Tagbanua / Taganua",
  "Tagbanua Kalamianen",
  "Tagbanua Tandulanen",
  "Talaandig",
  "Taloctok",
  "Tao't bato / Taut-Bato / Ken-ey",
  "Tau-buid",
  "Tboli",
  "Teduray",
  "Tigwahanon / Tagawahanon",
  "Tinananen",
  "Tingglan",
  "Tingguian / Itneg",
  "Tinglayan / Tonglayan",
  "Tinonanon Monuvu",
  "Tulgao",
  "Tuwali",
  "Ubo",
  "Ubo Manobo / Ubo-Manobo / Manobo Ubo",
  "Umayamnon",
  "Yakan",
  "Yogad"
] as const;

export const LIS_MOTHER_TONGUE_OPTIONS = [
  "Adasen",
  "Agta, Alabat Island",
  "Agta, Casiguran Dumagat",
  "Agta, Central Cagayan",
  "Agta, Dicamay",
  "Agta, Dupaninan",
  "Agta, Isarog",
  "Agta, Mt. Iriga",
  "Agta, Pahanan",
  "Agta, Pudtol",
  "Agta, Umiray Dumaget",
  "Agta, Villa Viciosa",
  "Agutaynen",
  "Akeanon Bukidnon",
  "Akeanon/Aklanon/Inakeanon",
  "Aklanon",
  "Alangan",
  "Alta, Northern",
  "Alta, Southern",
  "American Sign Laguage",
  "Arabic",
  "Arta",
  "Ati/Inati",
  "Atta, Faire",
  "Atta, Pamplona",
  "Ayta, Abellen",
  "Ayta, Ambala",
  "Ayta, Mag-antsi",
  "Ayta, Mag-Indi",
  "Ayta, Magbukun",
  "Ayta, Sorsogon",
  "Ayta, Tayabas",
  "Bag-o",
  "Balangao",
  "Balatok",
  "Bantoanon, Asi",
  "Batak",
  "Belwang",
  "Bikol",
  "Bikol Partido",
  "Bikol, Buhi’non",
  "Bikol, Central",
  "Bikol, Libon",
  "Bikol, Miraya",
  "Bikol, Northern Catanduanes",
  "Bikol, Rinconada",
  "Bikol, Southern Catanduanes",
  "Bikol, West Albay",
  "Binukid",
  "Bisakol",
  "Blaan",
  "Blaan, Sarangani",
  "Bol-anon",
  "Bolinao",
  "Buhid",
  "Butuanon",
  "Caluyanun",
  "Capiznon",
  "Cebuano",
  "Cebuano / Sinugbuanong Binisay",
  "Cebuano/Kana/Sinugboanong Bini",
  "Chabacano",
  "Chinese Cantonese",
  "Chinese Fookien",
  "Chinese Mandarin",
  "Cuyonon",
  "Davawenyo",
  "Dumagat, Remontado",
  "English",
  "Filipino",
  "Gaddang",
  "Giangan",
  "Gubang",
  "Hanunoo",
  "Higaonon",
  "Hiligaynon",
  "I-wak",
  "Ibaloi",
  "Ibanag",
  "Ibatan",
  "Ifugao, Amganad",
  "Ifugao, Batad",
  "Ifugao, Mayoyao/Ayangan",
  "Ifugao, Tuwali",
  "Ilocano",
  "Iloko",
  "Ilongot",
  "Inabaknon",
  "Inonhan",
  "Iranun",
  "Iraya",
  "Isinai",
  "Isnag",
  "Isneg",
  "Itawit",
  "Itneg, Banao",
  "Itneg, Binongan",
  "Itneg, Inlaod",
  "Itneg, Maeng",
  "Itneg, Masadiit",
  "Itneg, Muyadan",
  "Ivatan",
  "Ivatan-Itbayaten",
  "Kagayanen",
  "Kalagan",
  "Kalagan, Kagan",
  "Kalanguya",
  "Kalinga, Butbut",
  "Kalinga, Limos",
  "Kalinga, Lubuagan",
  "Kalinga, Mabaka Valley",
  "Kalinga, Majukayang",
  "Kalinga, Southern",
  "Kalinga, Tanudan",
  "Kallahan, Kayapa",
  "Kallahan, Keley-i",
  "Kallahan, Tinoc",
  "Kamayo",
  "Kankanaey",
  "Kankanay, Northern (aplaiy)",
  "Kapampangan",
  "Karao",
  "Kasiguranin",
  "Katabaga",
  "Kinamayo",
  "Kinaray-a",
  "Leytenio",
  "Lumad",
  "Mabaka",
  "Maguindanao",
  "Maguindanaoan",
  "Malaueg-Rizal",
  "Mandaya",
  "Manide",
  "Manobo",
  "Manobo Agusan",
  "Manobo Ata",
  "Manobo kinamiguin",
  "Manobo Matigsalog",
  "Manobo Western Bukidnon",
  "Manobo, Ata",
  "Manobo, Dibabawon",
  "Manobo, Ilianen",
  "Manobo, Matigsalug",
  "Manobo, Obo",
  "Manobo, Rajah Kabunsuwan",
  "Manobo, Sarangani",
  "Manobo, Western Bukidnon",
  "Manovo Ilanen",
  "Mansaka",
  "Mapun",
  "Maranao",
  "Masbatenyo / Minasbate",
  "Matigsalog",
  "Minamanwa",
  "Minanobo, Agusan / Surigao",
  "Molbog",
  "Nihonggo (Japanese)",
  "Other Filipino Language",
  "Other Foreign Language",
  "Palawano, Brooke’s Point",
  "Palawano, Central",
  "Palawano, Southwest",
  "Pampangan/ Kapampangan/ Pampan",
  "Pangasinan",
  "Paranan",
  "Philippine Sign Language",
  "Ratagnon",
  "Romblomanon",
  "Sama, Balangingih",
  "Sama, Central",
  "Sama, Pangutaran",
  "Sama, Southern",
  "Sambal",
  "Sambal, Botolan",
  "Sangil",
  "Sangir",
  "Sinurigaonon",
  "Sorsoganon, Northern",
  "Sorsoganon, Southern",
  "Spanish",
  "Subanen Eastern",
  "Subanen Northern",
  "Subanen, Central",
  "Subanen, Southern",
  "Subanon, Kolibugan",
  "Subanon, Western",
  "Sulod",
  "Taandig",
  "Tadyawan",
  "Tagabawa",
  "Tagakaulo",
  "Tagalog",
  "Tagbanwa",
  "Tagbanwa, Calamian",
  "Tagbanwa, Central",
  "Tandaganon / Tagaon-on",
  "Tausug",
  "Tawbuid, Eastern",
  "Tawbuid, Western",
  "Tboli",
  "Teduray",
  "Tigwahanon",
  "Umayamnon",
  "Waray",
  "Yakan",
  "Ybanag",
  "Yogad",
  "Ytawis"
] as const;

export const LIS_RELIGION_OPTIONS = [
  "Buddhism",
  "Christianity",
  "Hinduism",
  "Indigenous Religion",
  "Islam",
  "Judaism",
  "No Religion",
  "Not disclosed",
  "Others",
  "Sikhism",
  "Taoism",
] as const;
